DROP TABLE Agencia CASCADE;

DROP TABLE Voo CASCADE;

DROP TABLE CompanhiaAerea CASCADE ;

DROP TABLE Aviao CASCADE;

DROP TABLE Escala CASCADE;

DROP TABLE Passagem CASCADE;

DROP TABLE Embarque CASCADE;

DROP TABLE CEP CASCADE;

DROP TABLE Hotel CASCADE;

DROP TABLE Clientes CASCADE;

DROP TABLE AvaliacaoVoo CASCADE;

DROP TABLE PacoteViagem CASCADE;

DROP TABLE Desconto CASCADE;

DROP TABLE Gerar CASCADE;

DROP TABLE AvaliacaoPacote CASCADE;

DROP TABLE PacotePremium CASCADE;

DROP TABLE PacotePadrao CASCADE;

DROP TABLE AvaliacaoHotel CASCADE;

DROP TABLE Contem CASCADE;