CREATE TABLE Agencia (
	CNPJ VARCHAR(20),
    Nome VARCHAR(80) UNIQUE,
	Efetivos INT DEFAULT 0 NOT NULL,
    naoEfet INT  DEFAULT 0 NOT NULL,
    PRIMARY KEY (CNPJ)
);

CREATE TABLE CompanhiaAerea (
	CNPJ VARCHAR(20) UNIQUE,
    CodBarras INT UNIQUE,
    Numero INT UNIQUE,
    Nome VARCHAR(80) UNIQUE NOT NULL,
	Numero_SAC1 VARCHAR(20) NOT NULL,
    Numero_SAC2 VARCHAR(20),
    PRIMARY KEY(CNPJ, CodBarras, Numero)
);

CREATE TABLE Aviao (
	CodAviao INT,
    Modelo INT UNIQUE,
    Cor VARCHAR(20) NOT NULL,
    TempoFunc INT DEFAULT 0  NOT NULL,
    CNPJ VARCHAR(20),
    PRIMARY KEY (CodAviao),
    FOREIGN KEY (CNPJ) REFERENCES CompanhiaAerea(CNPJ)
);

CREATE TABLE Voo (
	Numero INT,
    Aviao INT DEFAULT 0,
    PRIMARY KEY (Numero),
	FOREIGN KEY (Aviao) REFERENCES Aviao(CodAviao)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE Escala(
	CodEscala INT,
    Partida VARCHAR(50) NOT NULL,
    Destino VARCHAR(50) NOT NULL,
    Preco FLOAT DEFAULT 0.0 NOT NULL,
    PRIMARY KEY (CodEscala)
);

CREATE TABLE Passagem(
	CodBarras INT UNIQUE,
    Numero INT UNIQUE,
    CodPertence INT NOT NULL,
    CodEscala INT DEFAULT 0,
    PRIMARY KEY (CodBarras, Numero),
    FOREIGN KEY (CodEscala) REFERENCES Escala(CodEscala)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE Embarque(
	NumeroVoo INT UNIQUE,
    CodBarras INT UNIQUE,
    DataEmb DATE NOT NULL,
    Plataforma INT DEFAULT 1 NOT NULL,
    PRIMARY KEY (NumeroVoo, CodBarras),
    FOREIGN KEY (NumeroVoo) REFERENCES Voo(Numero)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (CodBarras) REFERENCES Passagem(CodBarras)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE CEP (
	NumeroCEP VARCHAR(50),
    Cidade VARCHAR(50) NOT NULL,
    Estado VARCHAR(50) NOT NULL,
    PRIMARY KEY (NumeroCEP)
);

CREATE TABLE Hotel (
	CNPJ VARCHAR(20),
    Nome VARCHAR(50) UNIQUE NOT NULL,
    Rua VARCHAR(50) NOT NULL,
    Bairro VARCHAR(50) NOT NULL,
    Numero INT UNIQUE NOT NULL,
    NumeroCEP VARCHAR(50) DEFAULT '62900-000',
    PRIMARY KEY  (CNPJ),
    FOREIGN KEY (NumeroCEP) REFERENCES CEP(NumeroCEP)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE Clientes (
	CPF VARCHAR(20),
    DataNasc DATE NOT NULL,
    codVoo INT,
    codHotel INT,
    Passageiros INT DEFAULT 0 NOT NULL,
    Poltrona INT UNIQUE DEFAULT 1 NOT NULL,
    codPassagem INT,
    Nome VARCHAR(80) UNIQUE NOT NULL,
    Nota INT CHECK(Nota > 0 and nota < 11) NOT NULL,
	Resenha VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (codVoo) REFERENCES Voo(Numero)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (codHotel) REFERENCES Hotel(Numero)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (codPassagem) REFERENCES Passagem(Numero)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE AvaliacaoVoo (
	CPF VARCHAR(20),
    Numero INT,
    Nota INT CHECK(Nota > 0 and nota < 11) NOT NULL,
    Resenha VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY (CPF, Numero),
    FOREIGN KEY (CPF) REFERENCES Clientes(CPF)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (Numero) REFERENCES Voo(Numero)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE PacoteViagem (
	Codigo INT,
    Nome VARCHAR(80) UNIQUE NOT NULL,
    Preco FLOAT DEFAULT 0.0 NOT NULL,
    PontTuris VARCHAR(200) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Pais VARCHAR(50) NOT NULL,
    PRIMARY KEY (Codigo)
);

CREATE TABLE Desconto (
	CPF VARCHAR(20),
    Codigo INT,
    Porcentagem INT DEFAULT 10 NOT NULL,
    PRIMARY KEY (CPF, Codigo),
    FOREIGN KEY (CPF) REFERENCES Clientes(CPF)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (Codigo) REFERENCES PacoteViagem(Codigo)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE Gerar(
	CPF VARCHAR(20),
    Codigo INT,
    PRIMARY KEY (CPF, Codigo),
    FOREIGN KEY (CPF) REFERENCES Clientes (CPF)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (Codigo) REFERENCES PacoteViagem (Codigo)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE AvaliacaoPacote (
	CPF VARCHAR(20),
    Codigo INT,
    Nota INT CHECK(Nota > 0 and Nota < 11) NOT NULL,
    PRIMARY KEY (CPF, Codigo),
    FOREIGN KEY (CPF) REFERENCES Clientes (CPF)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (Codigo) REFERENCES PacoteViagem (Codigo)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE PacotePremium (
	Codigo INT,
    Paises VARCHAR(100) NOT NULL,
    Beneficios VARCHAR(200),
    PRIMARY KEY (Codigo),
    FOREIGN KEY (Codigo) REFERENCES PacoteViagem(Codigo)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE PacotePadrao (
	Codigo INT,
    Pais VARCHAR(50) NOT NULL,
    PRIMARY KEY  (Codigo),
    FOREIGN KEY (Codigo) REFERENCES PacoteViagem (Codigo)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE AvaliacaoHotel (
	CodAv INT,
	CPF VARCHAR(20),
    CNPJ VARCHAR(20),
    Nota INT CHECK(Nota > 0 and Nota < 11) NOT NULL,
    Resenha VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY  (CodAv),
    FOREIGN KEY (CPF) REFERENCES Clientes (CPF)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (CNPJ) REFERENCES Hotel (CNPJ)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);

CREATE TABLE Contem (
    Codigo INT,
    codHotel INT,
    PRIMARY KEY (Codigo , codHotel),
    FOREIGN KEY (Codigo) REFERENCES PacoteViagem (Codigo)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE,
    FOREIGN KEY (codHotel) REFERENCES Hotel (Numero)
	ON DELETE SET DEFAULT
	ON UPDATE CASCADE
);